import mysql.connector

connection = mysql.connector.connect(user='root', password='Sanmaysud1012', host='localhost', database='dawki')

mycursor = connection.cursor()


while(True):
  print()
  print()

  print("""Which OLAP Query do you want to execute from the following:
  ================================================================
  1) Find the total revenue generated by each product sold
  2) Find the average rating of products sold in each order
  3) Find the average rating given by each customer to the products they ordered
  4) Find the top 5 products with the highest revenue
  5) Exit
  =================================================================
  """)
  x=int(input("Enter your choice here: "))
  if(x==1):
    mycursor.execute("""SELECT product_name, SUM(product_price * product_stock) as total_revenue
FROM product 
JOIN orders ON product.product_id = orders.product_id
GROUP BY product_name with ROLLUP;""")

    result = mycursor.fetchall()
    print("Product Name  ||  Total Revenue")
    print("====================================")
    for product_name, total_revenue in result:
      print(f"{product_name}  ||  {total_revenue}")

  elif(x==2):
    mycursor.execute("""SELECT order_id, AVG(product_rating) as avg_rating
FROM orders
JOIN product ON orders.product_id = product.product_id
GROUP BY order_id WITH ROLLUP;
    """)
    result = mycursor.fetchall()
    print("Order ID  ||  Average Rating")
    print("====================================")
    for id, avg_rating in result:
      print(f"{id}  ||  {avg_rating}")

  elif(x==3):
    mycursor.execute("""SELECT customer_id, AVG(rating) as avg_rating
FROM delivery_agent
JOIN delivery_system ON delivery_agent.agent_id = delivery_system.agent_id
GROUP BY customer_id with ROLLUP;""")
    result = mycursor.fetchall()
    print("Customer ID  ||  Average Rating")
    print("====================================")
    for id, avg_rating in result:
      print(f"{id}  ||  {avg_rating}")

  elif(x==4):
    mycursor.execute("""SELECT product_name, SUM(product_price * product_stock) as total_revenue
FROM product 
JOIN orders ON product.product_id = orders.product_id
GROUP BY product_name WITH ROLLUP
ORDER BY total_revenue DESC 
LIMIT 5;
""")
    result = mycursor.fetchall()
    print("Product Name  ||  Total Revenue")
    print("====================================")
    for product_name, total_revenue in result:
      print(f"{product_name}  ||  {total_revenue}")
    
  elif(x==5):
    break
